# Generated by Django 5.2.15 on 2026-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focususer',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available for new work'), ('LIMITED', 'Limited availability'), ('BUSY', 'Busy'), ('UNAVAILABLE', 'Not available')], default='AVAILABLE', max_length=12),
        ),
        migrations.AddField(
            model_name='focususer',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='focususer',
            name='show_assigned_projects',
            field=models.BooleanField(default=False),
        ),
    ]
