# Generated by Django 6.0.6 on 2026-06-20 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_core', '0005_videoproject_archived_at_and_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SCRIPT', 'Script'), ('ASSETS', 'Asset folder'), ('VOICE_LINES', 'Voice lines'), ('EDIT', 'Edit timeline'), ('REVIEW', 'Review link'), ('REFERENCE', 'Reference'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_resources', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='focus_core.videoproject')),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
    ]
