# Generated by Django 6.0.6 on 2026-06-20 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_core', '0007_projectnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INVITE_CREATED', 'Invite created'), ('INVITE_REVOKED', 'Invite revoked'), ('INVITE_ACCEPTED', 'Invite accepted'), ('MEMBER_ROLE', 'Member role changed'), ('MEMBER_REMOVED', 'Member removed'), ('MEMBER_LEFT', 'Member left')], max_length=16)),
                ('message', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_group_notifications', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_notifications', to='focus_core.productiongroup')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='focus_core__recipie_8bc21f_idx')],
            },
        ),
    ]
